version: '3'
services:
  wps:
    build: .
    image: pcic/sandpiper
    ports:
      - "8101:5003"
    volumes:
      - /storage/data/climate/downscale/BCCAQ2/:/storage/data/climate/downscale/BCCAQ2/

# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
