version: '3.0'
services:
  sandpiper-dev:
    image: pcic/sandpiper:latest
    container_name: sandpiper-dev
    env_file:
      - ./deployment.env
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30101:5000"
    volumes:
      - ./dev-component/wps.cfg:/wps.cfg
    restart: always

networks:
  default:
    external:
      name: pcicbr0


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
