version: '3.4'

services:
  sandpiper-dev:
    image: ${SANDPIPER_DEV_IMAGE}
    container_name: sandpiper-dev
    env_file:
      - ../../sandpiper/deployment.env
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30101:5000"
    volumes:
      - ../../sandpiper/pavics-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ../../sandpiper/pavics-component/sandpiper-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/sandpiper-magpie-permission.cfg:ro
    - ../../sandpiper/pavics-component/sandpiper-magpie-provider.cfg:/opt/local/src/magpie/config/providers/sandpiper-magpie-provider.cfg:ro

  proxy:
    volumes:
      - ../../sandpiper/pavics-component/sandpiper_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/sandpiper_canarie_api_monitoring.py:ro